// 
// CreateUsingsProject.cs
// 
//   Created: 2022-10-23-02:34:24
//   Modified: 2022-11-06-12:50:51
// 
//   Author: Justin Chase <justin@justinwritescode.com>
//   
//   Copyright © 2022 Justin Chase, All Rights Reserved
//      License: MIT (https://opensource.org/licenses/MIT)
// 

using System.Text;
using System.Xml;
namespace MSBuild.UsingsSdk;

using System.Xml.Linq;

public class CreateUsingsProject : MSBTask
{
    [Required]
    public string InputFile { get; set; } = string.Empty;
    [Required]
    public string OutputFile { get; set; } = string.Empty;

    public virtual IEnumerable<XDocument> Load(string path)
    {
        var project = XDocument.Load(path);
        return new [] { project }.Concat(project.Descendants("UsingsImport").SelectMany(x => Load(x.Attribute("Include").Value)));
    }

    public override bool Execute()
    {
        var allProjects = Load(InputFile);

        Console.WriteLine("Found " + allProjects.Count() + " imported projects to process");

        var usings = allProjects.SelectMany(project => project.Descendants("Using")).OrderBy(x => x.Attribute("Include").Value).ToArray();
        var projectReferences = allProjects.SelectMany(project => project.Descendants("ProjectReference")).OrderBy(x => x.Attribute("Include").Value).ToArray();
        var packageReferences = allProjects.SelectMany(project => project.Descendants("PackageReference")).OrderBy(x => x.Attribute("Include").Value).ToArray();
        var properties = allProjects.SelectMany(project => project.Descendants("PropertyGroup").Descendants()).OrderBy(x => x.Value).ToArray();

        Console.WriteLine("Usings: " + usings.Length);
        Console.WriteLine("ProjectReferences: " + projectReferences.Length);
        Console.WriteLine("packageReferences: " + packageReferences.Length);
        Console.WriteLine("properties: " + properties.Length);
        var usingsFile = new XDocument(
            new XElement("Project",
                new XComment("<auto-generated />"),
                new XComment("This code was generated by a tool.  Do not modify it."),
                new XComment("⬇️ Properties ⬇️"),
                new XElement("PropertyGroup",
                    properties),
                new XElement("ItemGroup",
                    new XAttribute("Label", "Usings"),
                    new XComment("⬇️ Usings ⬇️"),
                    usings),
                new XElement("ItemGroup",
                    new XAttribute("Label", "Package References"),
                    new XComment("⬇️ Package References ⬇️"),
                    packageReferences),
                new XElement("ItemGroup",
                    new XAttribute("Label", "Project References"),
                    new XComment("⬇️ Project References ⬇️"),
                    projectReferences)));
        Console.WriteLine("Properties: " + usingsFile.Descendants("PropertyGroup").Count());
        Console.WriteLine("packageReferences: " + usingsFile.Descendants("PackageReference").Count());

        using (var outFile = File.CreateText(OutputFile))
        {
            usingsFile.Save(outFile);
        }
        // File.CreateText(OutputFile).Write(usingsFile.ToString());
        Console.WriteLine(usingsFile.ToString());
        Console.WriteLine("Wrote file: " + OutputFile);

        // var projectFile = new XDocument();
        // projectFile.Add(new XElement("Project",
        //     new XComment("<auto-generated />"),
        //     new XComment("This code was generated by a tool.  Do not modify it."),
        //     new XElement("PropertyGroup",
        //         new XElement("TargetFramework", "netstandard1.0", new XAttribute("Condition", "'$(TargetFramework)' == ''")),
        //         new XElement("LangVersion", "latest", new XAttribute("Condition", "'$(LangVersion)' == ''"),
        //         new XElement("EnableCentralPackageVersions", "false"),
        //         new XElement("GeneratePackageOnBuild", "true"),
        //         new XElement("IsNuGetized", "true"))),
        //     new XElement("ItemGroup",
        //         new XAttribute("Label", "Usings File"),
        //         new XElement("PackageFile", new XAttribute("Include", OutputFile), new XAttribute("PackagePath", "build/" + Path.GetFileName(OutputFile))),
        //     new XElement("ItemGroup",
        //         new XAttribute("Label", "Package References"),
        //         new XElement("PackageReference", new XAttribute("Include", "NuGetizer"), new XAttribute("Version", "0.9.0"))))));
        // projectFile.WriteTo(new System.Xml.XmlTextWriter(File.CreateText(Path.ChangeExtension(OutputFile, ".nuproj"))));

        return true;
    }
}
